include:
  - project: 'drupalspoons/webmasters'
    # Best practice is to pin to a tag or a SHA1. https://docs.gitlab.com/ee/ci/yaml/#includefile
    ref: 1.6.0-rc3
    # The template below may be inspected at https://gitlab.com/drupalspoons/webmasters/-/blob/master/templates/.gitlab-ci.yml
    file: 'templates/.gitlab-ci.yml'

#
# Projects may override anything in the template above.
# The code below is specific to devel project. You dont need to copy it to your new project.
#

css_js_style:
  stage: test
  dependencies:
    - composer
  script:
    - cd web/core && yarn add eslint stylelint
    - composer stylelint
    - composer eslint -- --format junit --output-file junit-eslint.xml
  allow_failure: true
  artifacts:
    expose_as: junit
    expire_in: 6 mos
    paths:
      #- junit-stylelint.xml
      - junit-eslint.xml
    reports:
      junit: junit-eslint.xml

# Run tests on Drupal 9 by default.
composer:
  variables:
    DRUPAL_CORE_CONSTRAINT: ^9

# Add /webprofiler to ignored paths.
code_style:
  script:
    - PWD=$(pwd) && vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --runtime-set ignore_errors_on_exit 1 --ignore=$PWD/web/,$PWD/vendor/,$PWD/webprofiler/ --report-junit=junit.xml --report-full --report-summary

