include:
  - project: 'drupalcontrib/webmasters'
    # Best practice is to pin to a tag or a SHA1.
    ref: master
    file: 'templates/gitlab-ci.yml'

# Projects can override anything in the included template. See https://docs.gitlab.com/ee/ci/yaml/README.html#include
phpunit:
  artifacts:
    expire_in: 4 mos
