# Schema for the configuration files of the webprofiler module.

webprofiler.settings:
  type: config_object
  label: 'Webprofiler settings'
  mapping:
    exclude_paths:
      type: string
      label: 'Paths to exclude from profiling'
    intercept_redirects:
      type: boolean
      label: 'Intercept redirects'
